Pig Stack Trace
---------------
ERROR 6000: Output Location Validation Failed for: '/user/abhinavp/japan More info to follow:
Output directory /user/abhinavp/japan already exists

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 2042: Error in new logical plan. Try -Dpig.usenewlogicalplan=false.
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:313)
	at org.apache.pig.PigServer.compilePp(PigServer.java:1365)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1207)
	at org.apache.pig.PigServer.execute(PigServer.java:1201)
	at org.apache.pig.PigServer.access$100(PigServer.java:129)
	at org.apache.pig.PigServer$Graph.execute(PigServer.java:1528)
	at org.apache.pig.PigServer.executeBatchEx(PigServer.java:373)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:340)
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:115)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:172)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:144)
	at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:90)
	at org.apache.pig.Main.run(Main.java:500)
	at org.apache.pig.Main.main(Main.java:107)
Caused by: org.apache.pig.impl.logicalLayer.FrontendException: ERROR 6000: Output Location Validation Failed for: '/user/abhinavp/japan More info to follow:
Output directory /user/abhinavp/japan already exists
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:102)
	at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:76)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
	at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:50)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator.validate(InputOutputFileValidator.java:52)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:292)
	... 13 more
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory /user/abhinavp/japan already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:132)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:87)
	... 21 more
================================================================================
